// Generated by Le Thanh Tuan
(function ($) {
    $.extend({
        ColorLife: {
            IMGLoading: '<img src=\"/Content/Images/ajax-loader.gif\" border=\"0\" />',
            templateUrl: '/Content/templates/',
            imagesFolder: '/Content/images/',
            siteUrl: 'http://localhost',
            serviceUrl: '/api/',
            userId: 0,
            userEmail: '',
            yourIP: '',
            params: {},
            VietNamChar: [
           "aAeEoOuUiIdDyY",
           "áàạảãâấầậẩẫăắằặẳẵ",
           "ÁÀẠẢÃÂẤẦẬẨẪĂẮẰẶẲẴ",
           "éèẹẻẽêếềệểễ",
           "ÉÈẸẺẼÊẾỀỆỂỄ",
           "óòọỏõôốồộổỗơớờợởỡ",
           "ÓÒỌỎÕÔỐỒỘỔỖƠỚỜỢỞỠ",
           "úùụủũưứừựửữ",
           "ÚÙỤỦŨƯỨỪỰỬỮ",
           "íìịỉĩ",
           "ÍÌỊỈĨ",
           "đ",
           "Đ",
           "ýỳỵỷỹ",
           "ÝỲỴỶỸ"
            ],
            // HELPER //
            loader: function (isFade) {
                if (isFade) {
                    $('#progressBackgroundFilter').fadeIn();
                    $('#loadingbox').fadeIn();
                    $('#Loader').fadeIn();
                } else {
                    $('#progressBackgroundFilter').fadeOut();
                    $('#loadingbox').fadeOut();
                    $('#Loader').fadeOut();
                }
            },
            replaceUnicode: function (strInput) {
                for (i = 1; i < $.ColorLife.VietNamChar.length; i++) {
                    for (j = 0; j < $.ColorLife.VietNamChar[i].length; j++) {
                        strInput = strInput.replace($.ColorLife.VietNamChar[i][j], $.ColorLife.VietNamChar[0][i - 1]);
                    }
                }
                return strInput;
            },
            removeDiacriticsURL: function (s) {
                var str = $.ColorLife.replaceUnicode(s).toLowerCase();
                str = str.replace(/\-/g, '');
                str = str.replace(/ /g, '-');
                str = str.replace(/\?/g, '');
                str = str.replace(/@/g, '-');
                str = str.replace(/\//g, '-');
                str = str.replace(/\&/g, '-');
                str = str.replace(/\(/g, '-');
                str = str.replace(/\=/g, '-');
                str = str.replace(/\)/g, '-');
                str = str.replace(/\./g, '-');
                str = str.replace(/\;/g, '-');
                str = str.replace(/\:/g, '');
                str = str.replace(/\,/g, '-');
                str = str.replace(/\"/g, '');
                str = str.replace(/\'/g, '');

                //  var reg = /^([A-Za-z0-9_\-\.])+\@([A-Za-z0-9_\-\.])+\.([A-Za-z]{2,4})$/;
                // return reg.test(email);
                return str.trim();
            },
            getAliasURL: function (s) {
                var alias = $('#Alias');
                alias.val(jQuery.ColorLife.removeDiacriticsURL(s));
            },
            demoFunction: function () {
                alert($.ColorLife.userEmail);
            },

            notifyInfo: function (msg) {
                toastr.info(msg, 'Thông báo', options = { "closeButton": true, "positionClass": "toast-bottom-left" });
            },
            notifySuccess: function (msg) {
                toastr.success(msg, 'Thành công', options = { "closeButton": true, "positionClass": "toast-bottom-left" });
            },
            notifyError: function (msg) {
                toastr.warning(msg, 'Lỗi', options = { "closeButton": true, "positionClass": "toast-bottom-left" });
            },
            getObjects: function (obj, key, val) {
                var objects = [];
                for (var i in obj) {
                    if (!obj.hasOwnProperty(i)) continue;
                    if (typeof obj[i] == 'object') {
                        objects = objects.concat($.ColorLife.getObjects(obj[i], key, val));
                    } else
                        //if key matches and value matches or if key matches and value is not passed (eliminating the case where key matches but passed value does not)
                        if (i == key && obj[i] == val || i == key && val == '') { //
                            objects.push(obj);
                        } else if (obj[i] == val && key == '') {
                            //only add if the object is not already in the array
                            if (objects.lastIndexOf(obj) == -1) {
                                objects.push(obj);
                            }
                        }
                }
                return objects;
            },

            //return an array of values that match on a certain key
            getValues: function (obj, key) {
                var objects = [];
                for (var i in obj) {
                    if (!obj.hasOwnProperty(i)) continue;
                    if (typeof obj[i] == 'object') {
                        objects = objects.concat($.ColorLife.getValues(obj[i], key));
                    } else if (i == key) {
                        objects.push(obj[i]);
                    }
                }
                return objects;
            },

            //return an array of keys that match on a certain value
            getKeys: function (obj, val) {
                var objects = [];
                for (var i in obj) {
                    if (!obj.hasOwnProperty(i)) continue;
                    if (typeof obj[i] == 'object') {
                        objects = objects.concat($.ColorLife.getKeys(obj[i], val));
                    } else if (obj[i] == val) {
                        objects.push(i);
                    }
                }
                return objects;
            },

            // JSON Data Fomater
            formatJSONDate: function (jsonDate) {
                var d = new Date(parseInt(jsonDate.substr(6), 10));
                var nullDate = new Date(1001, 0, 1);
                if (d.getTime() <= nullDate.getTime()) {
                    return "";
                }
                else {
                    var m = d.getMonth() + 1;
                    var s = d.getDate() + "/" + m + "/" + d.getFullYear() + ' ' + d.getHours() + ':' + d.getMinutes() + ':' + d.getSeconds();
                    return s;
                }
            },
            stringCurrency: function (num) {
                num = num.toString().replace(/\$|\,/g, '');
                if (isNaN(num)) num = "0";
                sign = (num == (num = Math.abs(num)));
                num = Math.floor(num * 100 + 0.50000000001);
                cents = num % 100;
                num = Math.floor(num / 100).toString();
                if (cents < 10) cents = "0" + cents;
                for (var i = 0; i < Math.floor((num.length - (1 + i)) / 3) ; i++)
                    num = num.substring(0, num.length - (4 * i + 3)) + '.' + num.substring(num.length - (4 * i + 3));
                return num;
            },
            // Validate Email
            validateEmail: function (email) {
                var reg = /^([A-Za-z0-9_\-\.])+\@([A-Za-z0-9_\-\.])+\.([A-Za-z]{2,4})$/;
                return reg.test(email);
            },
            validatePassword: function (password) {
                // var reg = /^(?=.*\d)(?=.*[a-z])(?=.*[A-Z])(?=.*[@#$%^&*]).{6,20}.*$/;
                // return reg.test(password);
                return true;
            },
            validatePasswordConfirm: function (password1, password2) {
                if (password2 != password1)
                    return false;
                return true;
            },

            jsonWebLink_ToSelectList: function (obj) {
                var URL = $.ColorLife.serviceUrl + "JsonWebLink_ToSelectList";
                $.getJSON(URL, function (data) {
                    var items;// "<option value=''>--- Tỉnh / Thành phố ---</option>";
                    $.each(data, function (i, city) {
                        items += "<option value='" + city.Value + "'>" + city.Text + "</option>";
                    });
                    $(obj).html(items);
                });
            },

            // JsonWeatherCity_ToSelectList
            jsonWeatherCity_ToSelectList: function (obj) {
                var URL = $.ColorLife.serviceUrl + "JsonWeatherCity_ToSelectList";
                $.getJSON(URL, function (data) {
                    var items = "<option value=''>--- Tỉnh / Thành phố ---</option>";
                    $.each(data, function (i, city) {
                        items += "<option value='" + city.Value + "'>" + city.Text + "</option>";
                    });
                    $(obj).html(items);
                });
            },
            jsonWeatherCity_Selected: function (city, obj) {
                var myService = "JsonWeatherCity_Selected";

                $.ajax({
                    type: 'POST',
                    dataType: 'json',
                    contentType: "application/json; charset=utf-8",
                    url: $.ColorLife.serviceUrl + myService,
                    data: "{city:'" + city + "'}",
                    beforeSend: function () {
                        $(obj).html($.ColorLife.IMGLoading);
                    },
                    success: function (result) {
                        if (result.Success) {
                            var tp = '<b>' + result.Data.ThanhPho + '</b></br>';
                            var ngay1 = result.Data.Ngay1 + '</br>';
                            var ngay1dulieu = result.Data.Ngay1DuLieu;
                            $(obj).html(tp + ngay1 + ngay1dulieu);
                        }
                        else {
                            $(obj).html("Not Found");
                        }
                    },
                    error: function (errormessage) {
                        $(obj).html("Đang cập nhật");
                    }
                });

            },
            backToTop: function () {
                $(window).scroll(function () {
                    if ($(this).scrollTop() != 0) {
                        $('#toTop').fadeIn();
                    } else {
                        $('#toTop').fadeOut();
                    }
                });

                $('#toTop').click(function () {
                    $('body,html').animate({ scrollTop: 0 }, 800);
                });

            },
            goToTop: function () {
                $('#scroll_to_top').click(function () {
                    $('body,html').animate({ scrollTop: 0 }, 800);
                });
            },
            getToday: function () {
                var d = new Date();

                var month = d.getMonth() + 1;
                var day = d.getDate();

                var output = (day < 10 ? '0' : '') + day + '/' + (month < 10 ? '0' : '') + month + '/' + d.getFullYear();

                $(".today").html(output);
            },


            // 24/11/2014
            jsonUpdateHitsData: function (obj, id) {

                $.ajax({
                    url: $.ColorLife.serviceUrl + '/' + obj + '/UpdateHits/' + id,

                    type: "PUT",
                    contentType: "application/json; charset=utf-8",
                    dataType: "json",
                    async: true,

                    success: function (result) {
                        if (result.Success) {

                        }
                        else {
                        }
                    },
                    error: function (errormessage) {

                    }
                });
                return false;
            },
            // 12/12/2014
            jsonGetDataListContentByCategoryID: function (id, number, handler) {
                $.ajax({
                    type: "GET",
                    url: $.ColorLife.serviceUrl + "Application/GetContentByCategoryID/" + id + "?number=" + number,
                    // data: JSON.stringify(dto),
                    contentType: "application/json; charset=utf-8",
                    dataType: "json",
                    beforeSend: function () {
                        // $(obj).html($.ColorLife.IMGLoading);
                    },
                    success: function Success(result, status) {
                        handler(result.ListData);
                    },
                    error: function Error(request, status, error) {
                        //  $(obj).html(request.statusText);
                        return null;
                    }
                });
            },
            // API Helper 16/11/2014 //
            jsonGetDataObject: function (id, url, handler) {
                $.ajax({
                    type: "GET",
                    url: $.ColorLife.serviceUrl + "Application/" + url + "/" + id,
                    // data: JSON.stringify(dto),
                    contentType: "application/json; charset=utf-8",
                    dataType: "json",
                    beforeSend: function () {
                        // $(obj).html($.ColorLife.IMGLoading);
                    },
                    success: function Success(result, status) {
                        handler(result);
                    },
                    error: function Error(request, status, error) {
                        //  $(obj).html(request.statusText);
                        return null;
                    }
                });
            },
            jsonGetDataList: function (id, url, handler) {
                $.ajax({
                    type: "GET",
                    url: $.ColorLife.serviceUrl + "Application/" + url + "/" + id,
                    // data: JSON.stringify(dto),
                    contentType: "application/json; charset=utf-8",
                    dataType: "json",
                    beforeSend: function () {
                        // $(obj).html($.ColorLife.IMGLoading);
                    },
                    success: function Success(result, status) {
                        handler(result.ListData);
                    },
                    error: function Error(request, status, error) {
                        //  $(obj).html(request.statusText);
                        return null;
                    }
                });
            },
            // SETTING            
            jsonGetSettingValue: function (id, obj) {
                this.jsonGetDataObject(id, 'Setting', function (handler) {
                    $(obj).html(handler.Data.Value);
                });
            },             
            jsonGetCategoryMenu: function (obj) {
                $.ajax({
                    type: "GET",
                    url: $.ColorLife.serviceUrl + "Application/CategoryMenu/0?t=1&x=1&z=1",
                    // data: JSON.stringify(dto),
                    contentType: "application/json; charset=utf-8",
                    dataType: "json",
                    beforeSend: function () {
                        // $(obj).html($.ColorLife.IMGLoading);
                    },
                    success: function Success(result, status) {
                        $(obj).html(result.Data);
                    },
                    error: function Error(request, status, error) {
                        //  $(obj).html(request.statusText);
                        return null;
                    }
                });
            },

            

            // END HELPER //
            jsonUserValidateBeforeLogin: function (username) {
                var dto = { "nameOrEmail": username };
                $.ajax({
                    url: $.ColorLife.serviceUrl + "JsonUser_ValidateBeforeLogin",
                    data: JSON.stringify(dto),
                    type: "POST",
                    contentType: "application/json; charset=utf-8",
                    dataType: "json",

                    success: function (result) {
                        if (result.Success) {
                            $("#btnLogin").removeClass("disabled");
                        }
                        else {
                            $("#btnLogin").addClass("disabled");
                            alert(result.Message);
                        }
                    },
                    error: function (errormessage) {

                        alert(errormessage.responseText);

                    }
                });
                return false;
            },
            jsonUserGetByUserName: function (username) {
                var dto = { "username": username };
                $.ajax({
                    url: $.ColorLife.serviceUrl + "JsonUsers_GetByUserName",
                    data: JSON.stringify(dto),
                    type: "POST",
                    contentType: "application/json; charset=utf-8",
                    dataType: "json",

                    success: function (result) {
                        if (result.Success) {
                            alert(result.Message);
                        }
                        else {
                            alert(result.Message);
                        }
                    },
                    error: function (errormessage) {

                        alert(errormessage.responseText);

                    }
                });
                return false;
            },
            jsonUserGetByEmail: function (email) {
                var dto = { "email": email };
                $.ajax({
                    url: $.ColorLife.serviceUrl + "JsonUsers_GetByEmail",
                    data: JSON.stringify(dto),
                    type: "POST",
                    contentType: "application/json; charset=utf-8",
                    dataType: "json",

                    success: function (result) {
                        if (result.Success) {
                            alert(result.Message);
                        }
                        else {
                            alert(result.Message);
                        }
                    },
                    error: function (errormessage) {

                        alert(errormessage.responseText);

                    }
                });
                return false;
            },
            jsonUserResetPassword: function (email, passwordNew) {
                var dto = { "email": email, "passwordNew": passwordNew };
                $.ajax({
                    url: $.ColorLife.serviceUrl + "JsonUsers_ResetPassword",
                    data: JSON.stringify(dto),
                    type: "POST",
                    contentType: "application/json; charset=utf-8",
                    dataType: "json",
                    beforeSend: function () {
                        $(".span-update").html("<i class='icon-spinner icon-spin'></i>Updating...</span>");
                    },
                    success: function (result) {
                        if (result.Success) {
                            $.ColorLife.notify(true, 'Thành công', result.Message);
                        }
                        else {
                            $.ColorLife.notify(false, 'Thất bại', result.Message);
                        }
                    },
                    error: function (errormessage) {
                        //Hiển thị lỗi nếu xảy ra
                        alert(errormessage.responseText);
                        //alert("ERROR 500");
                    }
                });
                return false;
            },
            jsonUserChangePassword: function (id, password, passwordNew) {
                var dto = { "id": id, "password": password, "passwordNew": passwordNew };
                $.ajax({
                    url: $.ColorLife.serviceUrl + "JsonUsers_ChangePassword",
                    data: JSON.stringify(dto),
                    type: "POST",
                    contentType: "application/json; charset=utf-8",
                    dataType: "json",
                    beforeSend: function () {
                        $(".span-update").html("<i class='icon-spinner icon-spin'></i>Updating...</span>");
                    },
                    success: function (result) {
                        if (result.Success) {
                            $.ColorLife.notify(true, 'Thành công', result.Message);
                        }
                        else {
                            $.ColorLife.notify(false, 'Thất bại', result.Message);
                        }
                    },
                    error: function (errormessage) {
                        //Hiển thị lỗi nếu xảy ra
                        alert(errormessage.responseText);
                        //alert("ERROR 500");
                    }
                });
                return false;
            },
            jsonUserChangePassword2: function (email, password, passwordNew) {
                var dto = { "email": email, "password": password, "passwordNew": passwordNew };
                $.ajax({
                    url: $.ColorLife.serviceUrl + "JsonUsers_ChangePassword",
                    data: JSON.stringify(dto),
                    type: "POST",
                    contentType: "application/json; charset=utf-8",
                    dataType: "json",
                    beforeSend: function () {
                        $(".span-update").html("<i class='icon-spinner icon-spin'></i>Updating...</span>");
                    },
                    success: function (result) {
                        if (result.Success) {
                            $("#changepassok").show();
                        }
                        else {
                            $("#changepasserror").show();
                        }
                    },
                    error: function (errormessage) {
                        //Hiển thị lỗi nếu xảy ra
                        alert(errormessage.responseText);
                        //alert("ERROR 500");
                    }
                });
                return false;
            },

            jsonUserAddUsersToRoles: function (id, rId) {
                var dto = { "userId": id, "roleId": rId };
                $.ajax({
                    url: $.ColorLife.serviceUrl + "JsonUsers_AddToRoles",
                    data: JSON.stringify(dto),
                    type: "POST",
                    contentType: "application/json; charset=utf-8",
                    dataType: "json",
                    beforeSend: function () {
                        $(".span-update").html("<i class='icon-spinner icon-spin'></i>Updating...</span>");
                    },
                    success: function (result) {
                        if (result.Success) {
                            $.ColorLife.notify(true, 'Thành công', result.Message);
                        }
                        else {
                            $.ColorLife.notify(false, 'Thất bại', result.Message);
                        }
                    },
                    error: function (errormessage) {
                        //Hiển thị lỗi nếu xảy ra
                        alert(errormessage.responseText);
                        //alert("ERROR 500");
                    }
                });
                return false;
            },
            jsonUserRemoveUsersFromRoles: function (obj) {
                var table = $(obj).closest("table").attr("id");
                var row = $(obj).closest("tr");
                var id = row.attr("id");
                var rId = row.attr("data-role");
                var dto = { "userId": id, "roleId": rId };
                $.ajax({
                    url: $.ColorLife.serviceUrl + "JsonUsers_RemoveFromRoles",
                    data: JSON.stringify(dto),
                    type: "POST",
                    contentType: "application/json; charset=utf-8",
                    dataType: "json",
                    beforeSend: function () {
                        $(".span-update").html("<i class='icon-spinner icon-spin'></i>Updating...</span>");
                    },
                    success: function (result) {
                        if (result.Success) {
                            row.remove();
                            $.ColorLife.notify(true, 'Thành công', result.Message);
                        }
                        else {
                            $.ColorLife.notify(false, 'Thất bại', result.Message);
                        }
                    },
                    error: function (errormessage) {
                        //Hiển thị lỗi nếu xảy ra
                        alert(errormessage.responseText);
                        //alert("ERROR 500");
                    }
                });
                return false;
            },
            jsonGetMainMenu: function (obj) {
                $.ajax({
                    type: "GET",
                    url: $.ColorLife.serviceUrl + "Application/GetMainMenu/1?s=1",
                    // data: JSON.stringify(dto),
                    contentType: "application/json; charset=utf-8",
                    dataType: "json",
                    beforeSend: function () {
                        // $(obj).html($.ColorLife.IMGLoading);
                    },
                    success: function Success(result, status) {
                        $(obj).html(result.Data);
                    },
                    error: function Error(request, status, error) {
                        //  $(obj).html(request.statusText);
                        return null;
                    }
                });
            },
            
           
                     
            jsonGetBySlideShow: function (handlerData) {
                $.ajax({
                    type: "GET",
                    url: $.ColorLife.serviceUrl + "GallerySlider/GetBySlideShow/1?x=1",
                    // data: JSON.stringify(dto),
                    contentType: "application/json; charset=utf-8",
                    dataType: "json",
                    beforeSend: function () {
                        // $(obj).html($.ColorLife.IMGLoading);
                    },
                    success: function Success(result, status) {
                        handlerData(result.ListData);
                    },
                    error: function Error(request, status, error) {
                        //  $(obj).html(request.statusText);
                        return null;
                    }
                });
            },
            // LOAD DATA TEMPLATE

            // 25/11/2014
            jsonStaff_openModal: function (id) {

                
                $.ajax({
                    type: "GET",
                    url: $.ColorLife.serviceUrl + "Organization/Single/"+id,                    
                    contentType: "application/json; charset=utf-8",
                    dataType: "json",
                    beforeSend: function () {
                        // $(obj).html($.ColorLife.IMGLoading);
                    },
                    success: function Success(result, status) {
                        var title = ' <h4 class="modal-title">'+result.Data.Item.Name+'</h4>';
                        title+=' <b>Văn phòng: '+result.Data.Item.Address+'</b><br />';
                        title += '<b>Điện thoại: </b> <a href="tel:' + result.Data.Item.Phone + '">' + result.Data.Item.Phone + '</a><br />';
                        title += ' <b>Email:  ' + result.Data.Item.Email + '</b><br />';
                        title += '<b>Website</b>: <a href="' + result.Data.Item.Website + '">' + result.Data.Item.Website + '</a>';

                        $('#myOrgModal .title').html(title);
                        var html = '';
                        $.each(result.Data.ListStaff, function (i, item) {
                            html += ' <div class="media">';
                            html += '<a class="media-right" href="#"><img title="' + item.Staff.FullName2 + '" class="img-thumbnail" src="' + item.Staff.Image + '"  width="82"/>      </a>';
                            html += ' <div style="padding-left:5px" class="media-body">';
                            html+=' <h4 class="media-heading">'+item.Staff.FullName2+'</h4>';
                            html+=item.Staff.Position+' <br>';
                            html += '<i class="fa fa-envelope"></i> ' + item.Staff.Email;
                            html += ' </div>';
                            html += ' </div>';
                           
                        });
                        $('#myOrgModal .modal-body').html(html);
                        $('#myOrgModal .modal-footer .detail').attr('href', '/Organization/Single/'+id);
                        
                    },
                    error: function Error(request, status, error) {
                        //  $(obj).html(request.statusText);
                        return null;
                    }
                });
                $('#myOrgModal').modal('show');

            },

            // Load Data Template - Le Thanh Tuan 22/6/2013
            jsonNotice_openModal: function (id) {

                var dto = { "id": id };
                $.ajax({
                    type: "POST",
                    url: $.ColorLife.serviceUrl + "JsonNotice_GetByID",
                    data: JSON.stringify(dto),
                    contentType: "application/json; charset=utf-8",
                    dataType: "json",
                    beforeSend: function () {
                        // $(obj).html($.ColorLife.IMGLoading);
                    },
                    success: function Success(result, status) {
                        // alert(result.Data.NoticeID);
                        $('#myNoticeModal .title').html(result.Data.Name);
                        $('#myNoticeModal .modal-body').html(result.Data.FullText);

                    },
                    error: function Error(request, status, error) {
                        //  $(obj).html(request.statusText);
                        return null;
                    }
                });
                $('#myNoticeModal').modal('show');

            },
            jsonAuction_getById: function (id) {
                var dto = { "id": id };
                $.ajax({
                    type: "POST",
                    url: $.ColorLife.serviceUrl + "JsonAuction_GetByID",
                    data: JSON.stringify(dto),
                    contentType: "application/json; charset=utf-8",
                    dataType: "json",
                    beforeSend: function () {
                        // $(obj).html($.ColorLife.IMGLoading);
                    },
                    success: function Success(result, status) {
                        // alert(result.Data.NoticeID);
                        return result;
                    },
                    error: function Error(request, status, error) {
                        //  $(obj).html(request.statusText);
                        return null;
                    }
                });

            },
            jsonAuction_openModal: function (id) {
                var dto = { "id": id };
                $.ajax({
                    type: "POST",
                    url: $.ColorLife.serviceUrl + "JsonAuction_GetByID",
                    data: JSON.stringify(dto),
                    contentType: "application/json; charset=utf-8",
                    dataType: "json",
                    beforeSend: function () {
                        // $(obj).html($.ColorLife.IMGLoading);
                    },
                    success: function Success(result, status) {
                        // alert(result.Data.NoticeID);
                        var obj = $('#myAuctionModal');
                        obj.find('.title').html(result.Data.Name);
                        obj.find('.modal-body .thumbnail').attr("src", result.Data.Image);
                        obj.find('.modal-body .viewdetail').attr("href", "/Auction/View/" + result.Data.AuctionID);
                        obj.find('.modal-body .cuurentprice').html($.ColorLife.stringCurrency(result.Data.PriceNow));
                        obj.find('.modal-body .biders').html(result.Data.Bidders + ' bids');
                        obj.find('.modal-body .category').html(result.Data.Category.Name);
                        obj.find('.modal-body .createdby').html(result.Data.Users.UserName);

                        obj.find('.modal-body .condition').html(result.Data.Condition);
                        obj.find('.modal-body .timecountdown_preview').attr('data-time', result.Data.TimerCountDown);

                        obj.find('.modal-body .timeago').attr("title", $.ColorLife.formatJSONDate(result.Data.DateCreated));
                        obj.find('.modal-body .timeago').html($.ColorLife.formatJSONDate(result.Data.DateCreated));

                        var date_preview = new Date($('.timecountdown_preview').attr('data-time'));
                        //  alert(date_preview);

                        obj.find('.modal-body .timecountdown_preview').countdown({ until: date_preview, compact: true, format: 'HMS' });


                        if (result.ListData.length > 0) {
                            var similar = '<b>Đấu giá liên quan&nbsp;</b>'
                            $.each(result.ListData, function (i, item) {
                                similar += '<a href="/Auction/View/' + item.AuctionID + '" rel="tooltip" title="' + item.Name + '">';
                                similar += '<img src="' + item.Image + '"/></a>&nbsp;';
                            });
                            obj.find('.modal-footer .similar').html(similar);
                        }
                        else {
                            obj.find('.modal-footer .similar').html("<b class='pull-left'>Không có đấu giá liên quan.</b>");
                        }
                        obj.find('.btnLike').click(function () {
                            $.ColorLife.jsonAuction_AddToWishList(result.Data.AuctionID);
                        });
                        // OnClose Modal Event
                        obj.on('hidden', function () {
                            obj.find(' .modal-body .timecountdown_preview').countdown('destroy');
                        });
                    },
                    error: function Error(request, status, error) {
                        $(obj).html(request.statusText);
                        return null;
                    }
                });
                $('#myAuctionModal').modal('show');

            },
            jsonContact_GetNewMessage: function () {
                var obj = $('#getNewMessage');
                $.ajax({
                    type: "POST",
                    url: $.ColorLife.serviceUrl + "JsonContact_GetNewMessage",
                    // data: JSON.stringify(dto),
                    contentType: "application/json; charset=utf-8",
                    dataType: "json",
                    beforeSend: function () {
                        // $(obj).html($.ColorLife.IMGLoading);
                    },
                    success: function Success(result, status) {
                        // alert(result.Data.NoticeID);

                        if (result.ListData.length > 0) {
                            obj.find('span.badge').html(result.ListData.length);
                            obj.find('ul>li.nav-header').html('<i class="icon-envelope-alt"></i>' + result.ListData.length + ' tin nhắn');
                            // obj.find('ul').append(result.ListData.length);


                            var list = '';
                            $.each(result.ListData, function (i, item) {

                                list += '<li><a href="Admin/Contact/Edit/' + item.ContactID + '"><img src="/images/avatars/avatar.png" class="msg-photo" alt="" />';
                                list += ' <span class="msg-body">';

                                list += ' <span class="msg-title">';
                                list += '<span class="blue">' + item.FullName + ': </span>';
                                list += item.Subject;
                                list += '</span>';

                                list += '<span class="msg-time"><i class="icon-time"></i>';
                                list += ' <span>' + $.ColorLife.formatJSONDate(item.DateCreated) + '</span>';
                                list += '</span>';
                                list += '</span></a></li>';

                            });
                            obj.find('ul').append(list);
                            obj.find('ul').append('<li><a href="/Admin/Contact">Tất cả liên hệ  <i class="icon-arrow-right"></i></a></li>');
                        }
                        else {
                            obj.find('ul').append("<li>Không có tin nhắn.</li>");
                        }

                    },
                    error: function Error(request, status, error) {
                        $(obj).html(request.statusText);
                        return null;
                    }
                });

            },
            
           
            jsonDistrict_ToSelectListByProvinceID: function () {
                $("#ProvinceID").change(function () {
                    var URL = $.ColorLife.serviceUrl + "JsonDistrict_ToSelectListByProvinceID";
                    $.getJSON(URL + '/' + $("#ProvinceID").val(), function (data) {
                        var items = "<option value=''>--- Quận / huyện ---</option>";
                        $.each(data, function (i, state) {
                            items += "<option value='" + state.Value + "'>" + state.Text + "</option>";
                        });
                        $('#DistrictID').html(items);
                    });
                });
            },
            jsonProvince_ToSelectListByCountryID: function () {
                $("#CountryID").change(function () {
                    var URL = $.ColorLife.serviceUrl + "JsonProvince_ToSelectListByCountryID";
                    $.getJSON(URL + '/' + $("#CountryID").val(), function (data) {
                        var items = "<option value=''>--- Tỉnh / Thành phố ---</option>";
                        $.each(data, function (i, state) {
                            items += "<option value='" + state.Value + "'>" + state.Text + "</option>";
                        });
                        $('#ProvinceID').html(items);
                    });
                });
            },

            jsonDistrict_ToSelectListByCurrentProvinceID: function (id) {
                var URL = $.ColorLife.serviceUrl + "JsonDistrict_ToSelectListByProvinceID/" + id;
                $.getJSON(URL, function (data) {
                    var items = "<option value=''>--- Quận / huyện ---</option>";
                    $.each(data, function (i, state) {
                        items += "<option value='" + state.Value + "'>" + state.Text + "</option>";
                    });
                    $('#DistrictID').html(items);
                });

            },

            
            jsonArticle_AjaxSearch: function (q) {
                if (q.length == 0) {
                    $('#suggestions').fadeOut();
                    // Hide the suggestions box
                }
                else {
                    $.ajax({
                        type: "POST",
                        url: $.ColorLife.serviceUrl + "JsonArticle_Search",
                        data: JSON.stringify({ "q": "" + q + "" }),
                        contentType: "application/json; charset=utf-8",
                        dataType: "json",
                        beforeSend: function () { $('#suggestions').html($.ColorLife.IMGLoading); },
                        success: function Success(result, status) {
                            if (result.Success && result.ListData.length > 0) {
                                $('#suggestions').setTemplateURL($.ColorLife.templateUrl + 'article_searchmodule.html');
                                $('#suggestions').processTemplate(result.ListData);
                                //$('#suggestions').html(data); // Fill the suggestions box

                                $('#suggestions').fadeIn(); // Show the suggestions box
                            }
                            else {
                                $('#suggestions').fadeOut();
                            }
                        },
                        error: function Error(request, status, error) {
                            $('#suggestions').html(request.statusText);
                        }
                    });
                }
            },
            jsonAuction_AjaxSearch: function (q) {
                if (q.length == 0) {
                    $('#suggestions').fadeOut();
                    // Hide the suggestions box
                }
                else {
                    $.ajax({
                        type: "POST",
                        url: $.ColorLife.serviceUrl + "JsonAuction_Search",
                        data: JSON.stringify({ "q": "" + q + "" }),
                        contentType: "application/json; charset=utf-8",
                        dataType: "json",
                        beforeSend: function () { $('#suggestions').html($.ColorLife.IMGLoading); },
                        success: function Success(result, status) {
                            if (result.Success && result.ListData.length > 0) {
                                $('#suggestions').setTemplateURL($.ColorLife.templateUrl + 'auction_searchmodule.html');
                                $('#suggestions').processTemplate(result.ListData);
                                //$('#suggestions').html(data); // Fill the suggestions box

                                $('#suggestions').fadeIn(); // Show the suggestions box
                            }
                            else {
                                $('#suggestions').fadeOut();
                            }
                        },
                        error: function Error(request, status, error) {
                            $('#suggestions').html(request.statusText);
                        }
                    });
                }
            },
            /*=========================*/ 
            jsonStatsData: function () {

                var myService = "JsonStats";

                var dto = {};
                $.ajax({
                    url: $.ColorLife.serviceUrl + myService,
                    data: JSON.stringify(dto),
                    type: "POST",
                    contentType: "application/json; charset=utf-8",
                    dataType: "json",
                    async: true,
                    beforeSend: $.ColorLife.loader(true),
                    complete: $.ColorLife.loader(false),
                    success: function (result) {
                        if (result.Success) {
                            $(".statscategory").html(result.Data.StatsBannerCategory);
                            $(".statslogo").html(result.Data.StatsLogo);
                            $(".statsusers").html(result.Data.StatsUsers);

                            //alert(result.Data.StatsBannerCategory);
                        }
                        else {
                            alert(result.Message);
                        }
                    },
                    error: function (errormessage) {
                        //Hiển thị lỗi nếu xảy ra
                        alert(errormessage.responseText);
                    }
                }); return false;

            },
            doUpload: function (action, preview, output) {

                new AjaxUpload(action, {
                    action: '/FileUpload.axd',
                    name: 'myFile',
                    data: { 'folder': '/Uploads/Images/' },
                    autoSubmit: true,
                    onSubmit: function (file, extension) {
                        if (!(extension && /^(jpg|png|jpeg|gif|bmp|JPG|PNG|JPEG|BMP|GIF)$/.test(extension))) {

                            alert('Only JPG, PNG or GIF files are allowed');

                            return false;
                        }

                        preview.attr('src', '/Content/images/bigloading.gif');

                        output.val('Loading...');
                        output.attr('disabled', true);
                        this.disable();

                    },
                    onComplete: function (file, response) {
                        preview.load(function () {
                            preview.unbind();
                        });
                        output.attr('disabled', false);
                        var resp = response;
                        resp = jQuery(resp).html();
                        preview.attr('src', resp);
                        this.enable();

                        output.val(resp);
                        if ($("#removefile").length > 0) {
                            $("#removefile").show();
                        }
                        return true;
                    }
                });
            },
            removeUpload: function (file) {
                var dto = { "file": file };
                $.ajax({
                    type: "POST",
                    url: "/DeleteFileHandler.axd?file=" + file,
                    data: JSON.stringify(dto),
                    contentType: "application/json; charset=utf-8",
                    dataType: "json",
                    beforeSend: function () {
                        // alert(file);
                    },//$.ColorLife.loader(true),
                    success: function Success(data, status) {

                        $.ColorLife.notify(true, 'Thành công', data.status);
                        $("#removefile").hide();
                    },
                    error: function Error(request, status, error) {
                        $.ColorLife.notify(false, 'Lỗi', request.statusText);
                    }
                });
                return false;
            },
            supportOnine: function () {
                $("#support_open_close").click(function () {

                    if ($('.d_suport_box').attr('title') != 'active') {
                        $('.d_suport_box').attr('title', 'active');
                        $(".d_suport_box").animate({ bottom: "109" }, "medium");
                        //  $(".d_suport_box").css('background', 'url("' + bgsrc + '") no-repeat scroll 1px -64px transparent');
                        $("#support_open_close").addClass("support_box_close");
                        $(".d_slide").animate({ bottom: "-15" }, "medium");
                    } else {
                        $('.d_suport_box').attr('title', '');
                        $(".d_suport_box").animate({ bottom: "-329" }, "medium");
                        // $(".d_suport_box").css('background', 'url("' + bgsrc + '") no-repeat scroll 0 0px transparent');
                        $("#support_open_close").removeClass("support_box_close");
                        $("#support_open_close").addClass("support_box_open");
                        $(".d_slide").animate({ bottom: "-454" }, "medium");
                    }
                });
            },
            json_loadjTemplate: function (divId) {
                var dto = {}; var myService = "JsonStats";
                $.ColorLife.loader(true);
                $.ajax({
                    type: "POST",
                    url: $.ColorLife.serviceUrl + myService,
                    data: JSON.stringify(dto),
                    contentType: "application/json; charset=utf-8",
                    dataType: "json",
                    beforeSend: $.ColorLife.loader(true),
                    success: function Success(data, status) {
                        $(divId).setTemplateURL($.ColorLife.templateUrl + 'jtemplate.html');
                        $(divId).processTemplate(data.d);
                        $.ColorLife.loader(false);

                    },
                    error: function Error(request, status, error) {
                        $(divId).html(request.statusText);
                    }
                });
            }


            // , tiep tuc ham khac            
        }// end ColorLife
    }); // end extend
})(jQuery);

 